FROM pipelinr-clients-node-base:latest AS build

FROM node:15.14.0-buster
WORKDIR /app

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
USER appuser:appuser

COPY --from=build /app /app
COPY ./js/run/worker/pushwithtiming.js /app/run/worker/pushwithtiming.js

CMD ["npm", "run", "worker:push"]