FROM pipelinr-clients-node-base:latest AS build

FROM node:15.14.0-buster
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
COPY --from=build /go/bin/router /go/bin/router
USER appuser:appuser

COPY ./js/run/worker/route.js ./run/worker/pushwithtiming.js

ENTRYPOINT ["node", "/app/run/worker/pushwithtiming.js"]