FROM golang:1.13 AS build

ENV GO111MODULE=on

WORKDIR /go/src

COPY go/go.mod .
COPY go/go.sum .
RUN go mod download
COPY . .

ENV USER=appuser
ENV UID=10001 
RUN adduser \    
    --disabled-password \    
    --gecos "" \    
    --home "/nonexistent" \    
    --shell "/sbin/nologin" \    
    --no-create-home \    
    --uid "${UID}" \    
    "${USER}"
