FROM pipelinr-clients-ruby-base:latest AS build

FROM ruby:3.0.2-slim-buster
WORKDIR /app

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
USER appuser:appuser

COPY --from=build /app /app
COPY ./ruby/run/worker/pushwithtiming.rb /app/run/worker/pushwithtiming.rb

CMD ["ruby", "/app/run/worker/pushwithtiming.rb"]